# Usa l'immagine ufficiale Oracle Database
FROM container-registry.oracle.com/database/express:latest

# Imposta le variabili d'ambiente necessarie
ENV ORACLE_HOME=/opt/oracle/product/19c/dbhome_1
ENV ORACLE_SID=e_commerce
ENV PDB_NAME=Nawen
ENV ORACLE_PASSWORD=password

# Crea una directory per i dati e imposta un volume
RUN mkdir -p /opt/oracle/database

# Imposta il volume per la persistenza dei dati
VOLUME ["/opt/oracle/database"]

# Esponi le porte per il database
EXPOSE 1521 5500

# Comando per avviare il database
CMD ["startup"]
