# Usa l'immagine ufficiale di Apache Cassandra
FROM cassandra:latest

# Imposta le variabili d'ambiente necessarie per la configurazione di Cassandra
ENV CASSANDRA_CLUSTER_NAME="ECommerceCluster"
ENV CASSANDRA_DC="datacenter1"
ENV CASSANDRA_RACK="rack1"
ENV CASSANDRA_SEEDS="127.0.0.1"
#Consente le comunicazioni CQL
ENV CASSANDRA_START_RPC="true" 

# Crea una directory per i dati di Cassandra
RUN mkdir -p /var/lib/cassandra/database

# Imposta il volume per la persistenza dei dati
VOLUME ["/var/lib/cassandra/database"]

# Esponi le porte di Cassandra
EXPOSE 7000 7001 7199 9042 9160

# Comando per avviare Cassandra
CMD ["cassandra", "-f"]
